# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

# This workflow will periodically check .NET nanoFramework dependencies and updates them in the repository it's running.

name: Update dependencies (round 2)

on:
  schedule:
    # Round 2/5: Executes 30 minutes after round 1 (02:30 UTC) to allow enough time for any changes to propagate.
    # (taking into account PR merge and build branch).
    - cron: '30 02 * * Mon,Wed'
  repository_dispatch:
    types: update-dependencies
  workflow_dispatch:

jobs:
  update-nuget-dependencies:
    name: nanoFramework
    uses: nanoframework/nf-tools/.github/workflows/update-dependencies.yml@main
    secrets: inherit
    with:
      timeout-minutes: 15 # The next round will start after (taking into account PR merge and build branch).
      workingDirectory: devices
      branchToPr: 'develop'      
      solutionsToCheck: |
        ShiftRegister.sln
        Card.sln
